language: android
android:
  components:
  - tools
  - platform-tools
  - build-tools-26.0.2
  - extra-android-m2repository
  - android-26
  - sys-img-armeabi-v7a-android-17
before_script: 
addons:
  sonarcloud:
    organization: "sockeqwe-github"
    token:
      secure: sG283mZs8szzBkWh2WGDBLuk3EM0jqkYFIolKaE/j906aUOBXvLYLJKd6Tx8oDg9QxijSRaLdpyj6sPDfyhmEOV9rEzJpZVgmfyDjRFgValyws4ASxN3TMRmb8ZGE5hBLuckCZJpHyz0xTe1fE7MmjNZOvztOOgTCsUASw9Yyt4=
    branches:
      - sonarqubeintegration
      - master
    github_token:
      secure: "cmPqeb1CXxWXwqkw+UCfDkKmes0duSsFlYjsD30JsvFDX+MfHhrrdOuRPc/lem9AgOG9UfqsFJbbucmFwJDWX5jcSIFXxEoIHw+qI8+jpPSNggfatiZyPJJgqC6zqWj47bpOdBSt7TSImeM8S3exgidy7kjPMvzHxV7QAUPoBXY="
jdk:
- oraclejdk8
licenses:
- android-sdk-license-.+
- android-sdk-license-c81a61d9
env:
  global:
  - MALLOC_ARENA_MAX=2
  - secure: gMFLK1oOnrmKo2BQyuc4q5JNbO9yZNzGXujUjMDZqY80PM17u1NHH+FtMtqHltGdHlysQGWOVEgCCaXKSjzUR/5oWX3Rx2o36sxFeFJTnv6Og1IfYaT+30yMNCw9dZwBgL/f9+MUcJGyg17Y4YJKiKP8f+2Zj8Cem8a1tTOv7z0=
  - secure: EtsL8IYW/+QFowKy/pM1pfc6XBz19AEPRv9+3I3vdHbLNzrEgAcQG/sfWwSwG8N9SyQ9HlgFpy+a4rT9y+vcT52izRviZbLKepCiGk2XyCrBasRy0ncbZBk4Mss1JPP2OFatsiEfEOrFo5rt1CnWapMUOwE7X5blCjrLtEjZRSA=
branches:
  except:
  - gh-pages
notifications:
  email: false
sudo: required
script: "./gradlew build sonarqube"
cache:
  directories:
  - "$HOME/.gradle"
  - '$HOME/.sonar/cache'
  - '$HOME/.m2/repository'
  - '.gradle'
after_failure:
- cat /home/travis/build/sockeqwe/mosby/mvp/build/outputs/lint-results-debug.xml
- cat /home/travis/build/sockeqwe/mosby/viewstate/build/outputs/lint-results-debug.xml
- cat /home/travis/build/sockeqwe/mosby/mvi/build/outputs/lint-results-debug.xml
after_success:
- ".buildscript/deploy_snapshot.sh"
