language: android
android:
  components:
  - build-tools-23.0.1
  - extra-android-m2repository
  - android-23
before_install:
- chmod +x .buildscript/deploy_snapshot.sh
jdk:
- oraclejdk8
env:
  global:
  - MALLOC_ARENA_MAX=2
  - secure: YelAaq0fTyrWjYWYlUOkuRbtoWdtBOq1zI+T5K6y+Xo0H0rycDA7ED+h6qHg27NBnZLIZpBSe4YlIz7cjgbxHUZsYrTAzH7Ue+80hNoml7+2upJWbtwHzovwlb/nSB9XlXCyI4dhjSjBOGLpGlt6c5lGTDg6NOOLj5QBdpLgfTYV82jIHrd3oRJeiLpgGzNQQ08ZGOr8a3cP7vqfinKWg6fsmbQS0gpp1CIBgeh8hyZ2ip/AlyOd4Imppn2XnBcac/VtKaaQn/Yxj9ZIyjAeVQdftWjsCe423z03pMkXvvCGbnT+IMl1it3UWlJ8kutxcW2Qm4AheYF6iivlvA0pJXE2K/knWZoBiLvQ8quHKzBYIu4alpXKZiwEv3BGsLBICBYwucQ+XZPYbhJFzggLDSZRoGR8xl8czy1xgrZcK096QsLmxKwHnhwkuoCnCKvkTai7lmxlHEEh7MlpLh4XhQT/2EIAlaHTA2hmvD+chUYLAemSCEhERHP6S0UaV9MDtBEJbY//GoYynu2xMXOivLzrpRLsforF6IE+1L2U40Jtad+IJQinGSj9b5is378tIIf1RL7GOAKpRGIktkJtrM2UteVRYnQsCnpPRj7bMfVp0NWb+sGe21vNBKCAOBDsum0hBs4KK5auKp11jwRAdrmxdk7qwnFX61z9H6kMxp0=
  - secure: a9IFeOcxyjzKVbp/XXv0KBxGGyelzZXkxZjN9hZI2LrSyNUnn9nvJjI6DGHLhEnTpBKPwBu5maM+DH4ZolxqAcU7hW3RNuP77XiSi/CNlgTmHJcDXda/d0RNfKBmSs+412DnwxepqFTt6TkxJn7uzm54wInyniWzNFpbi4s78j/w28D/bat3rHpa3dK86p/em3NC/B87rwFoszF2amKAmKXRJWJVxgaZco7vR11q86+CjqjnbZAvcFc88MATDCoIJ4S4WSGg/+thSyHqtUnRIDcrine96t1C60cINBn5TTnK923NxpkfgFBD+LZyDQnCXGOXUHNhW9TH1nBQS+8pC13fSuhlTEOtSPz0pKnsxln9Gbir9HBfhtmjwHC4P268pXMP5u1CqBzNIkqvFgkwOFzfMqEjCU+DzpvdN0MH1CjRLg1VPPmVtTaepcPkX4sySO841SoQmunXIZbzL/wlKeJEcWHiL8sH14XcEtjzFz2bKb2Ucu8WUIJyen4YfHZ4EoSQsjStgGPxjtDq5kI1g66vob5Rp0OsN41hZcCGq/bxPrcMRlPElLPIQkIIhyfFLp/8H6atVlsf0z79KewxjLcfGYEuLHcH5QFtUvhAgxxJ4eNmMLf3Dm07lNBKJlk6B0YTpYY1jzmeOQxOtKDgg0oNZS9iWZjcFeg5e0UYCOU=
branches:
  except:
  - gh-pages
notifications:
  email: false
sudo: required
script: gradle build --stacktrace
after_success:
- ".buildscript/deploy_snapshot.sh"
cache:
  directories:
  - "$HOME/.gradle"
