# Site settings
title:       Mosby
email:
author:      Hannes Dofrmann
description: "Model-View-Presenter (MVP) library for modern android apps"
keywords:    "Model-View-Presenter, MVP, mvp, mosby, android, architecture, software, clean architecture, mvc"
baseurl:     ""
url:         ""

# Google analytics
google_analytics: UA-63278523-1

# Optional features
animated:           false
show_related_posts: false
show_post_footers:  false
show_social_icons:  false

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname: mosby

# Social icons
github_username:
stackoverflow_id:
twitter_username:
google_plus_id:
linkedin_username:
angellist_username:
medium_id:
bitcoin_url:
paypal_url:
flattr_button:

# Post sharing icons
show_sharing_icons: true
share_text:
# Change to 'true' to enable individual icons
share_facebook: true
share_twitter: true
share_googleplus: true
share_linkedin: true
share_digg: false
share_tumblr: false
share_reddit: true
share_stumbleupon: false
share_hackernews: true

# Build settings
markdown:     kramdown
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:
sass:
  compressed: true
