version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-25-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "mvi/build.gradle" }}-{{ checksum  "mvi-common/build.gradle" }}-{{ checksum  "mvi-integration-test/build.gradle" }}-{{ checksum  "mvp/build.gradle" }}-{{ checksum  "mvp-common/build.gradle" }}-{{ checksum  "mvp-lce/build.gradle" }}-{{ checksum  "mvp-nullobject-presenter/build.gradle" }}-{{ checksum  "presentermanager/build.gradle" }}-{{ checksum  "sample/build.gradle" }}--{{ checksum  "sample-mail/build.gradle" }}-{{ checksum  "sample-mvi/build.gradle" }}-{{ checksum  "utils-fragment/build.gradle" }}-{{ checksum  "utils-fragment-integration-test/build.gradle" }}-{{ checksum  "viewstate/build.gradle" }}
 #     - run:
 #         name: Start Android Emulator (swarmer)
 #         command: ./.buildscript/swarmer/swarmer_start.sh         
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "mvi/build.gradle" }}-{{ checksum  "mvi-common/build.gradle" }}-{{ checksum  "mvi-integration-test/build.gradle" }}-{{ checksum  "mvp/build.gradle" }}-{{ checksum  "mvp-common/build.gradle" }}-{{ checksum  "mvp-lce/build.gradle" }}-{{ checksum  "mvp-nullobject-presenter/build.gradle" }}-{{ checksum  "presentermanager/build.gradle" }}-{{ checksum  "sample/build.gradle" }}--{{ checksum  "sample-mail/build.gradle" }}-{{ checksum  "sample-mvi/build.gradle" }}-{{ checksum  "utils-fragment/build.gradle" }}-{{ checksum  "utils-fragment-integration-test/build.gradle" }}-{{ checksum  "viewstate/build.gradle" }}
      - run:
          name: Build and Run Tests
          command: ./gradlew build lint test cAT
#      - run:
#          name: Stop Android Emulator (swarmer)
#          command: ./.buildscript/swarmer/swarmer_stop.sh
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results